services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
  elasticsearch:
    image: elasticsearch:9.3.2
  kibana:
    image: kibana:9.3.2
  rabbitmq:
    image: rabbitmq:4.2.0-rc.1-management
  redis:
    image: redis

  authservice.api:
    image: ${DOCKER_REGISTRY-}authserviceapi
    build:
      context: .
      dockerfile: AuthService/src/AuthService.Api/Dockerfile

  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService/src/ProductService.Api/Dockerfile

  logservice.api:
    image: ${DOCKER_REGISTRY-}logserviceapi
    build:
      context: .
      dockerfile: LogService/LogService.Api/Dockerfile

  logservice.worker:
    image: ${DOCKER_REGISTRY-}logserviceworker
    build:
      context: .
      dockerfile: LogService/LogService.Worker/Dockerfile

volumes:
  elastic_search_volume:
  rabbitmq_volume:
  




