services:
  
  mssql:
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Evaluation
    networks:
      - app-network
  
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_search_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
  
  kibana:
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - app-network

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  authservice.api:
    container_name: authserviceapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      
      - ConnectionStrings:SqlServer=${AUTH_SERVICE_DB_STRING}
      
      - RabbitMQOptions:Host=${RABBITMQ_HOST}
      - RabbitMQOptions:VirtualHost=${RABBITMQ_VIRTUAL_HOST}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}

      - AuthOptions:Issuer=${AUTH_SERVICE}
      - AuthOptions:SecurityKey=${ACCESS_TOKEN_SECURITY_KEY}
      - TokenOptions:Issuer=${AUTH_SERVICE}
      - TokenOptions:AccessTokenValidtyPeriod=${ACCESS_TOKEN_VALIDITY_PERIOD}
      - TokenOptions:RefreshTokenValidtyPeriod=${REFRESH_TOKEN_VALIDITY_PERIOD}
      - TokenOptions:SecurityKey=${ACCESS_TOKEN_SECURITY_KEY}
    ports:
      - "80"
    depends_on:
      - mssql
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network

  productservice.api:
    container_name: productserviceapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80

      - ConnectionStrings:SqlServer=${PRODUCT_SERVICE_DB_STRING}

      - RabbitMQOptions:Host=${RABBITMQ_HOST}
      - RabbitMQOptions:VirtualHost=${RABBITMQ_VIRTUAL_Host}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}

      - AuthOptions:Issuer=${AUTH_SERVICE}
      - AuthOptions:SecurityKey=${ACCESS_TOKEN_SECURITY_KEY}
      - Redis:Host=${REDIS}
    ports:
      - "80"
    depends_on:
      - mssql
      - rabbitmq
      - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network

  logservice.api:
    container_name: logserviceapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ElasticSearchOptions:Host=${ELASTIC_SEARCH}
    ports:
      - "80"
    depends_on:
      - elasticsearch
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network

  logservice.worker:
    container_name: logserviceworker
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ElasticSearchOptions:Host=${ELASTIC_SEARCH}

      - RabbitMQOptions:Host=${RABBITMQ_HOST}
      - RabbitMQOptions:VirtualHost=${RABBITMQ_VIRTUAL_Host}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}
    depends_on:
      - rabbitmq
      - elasticsearch
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - app-network

  gateway.api:
    container_name: gatewayapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80

      - RabbitMQOptions:Host=${RABBITMQ_HOST}
      - RabbitMQOptions:VirtualHost=${RABBITMQ_VIRTUAL_HOST}
      - RabbitMQOptions:Password=${RABBITMQ_PASSWORD}
      - RabbitMQOptions:UserName=${RABBITMQ_USERNAME}

      - AuthOptions:Issuer=${AUTH_SERVICE}
      - AuthOptions:SecurityKey=${ACCESS_TOKEN_SECURITY_KEY}

      - ReverseProxy:Clusters:user.cluster:Destinations:destination:Address=${AUTH_SERVICE}
      - ReverseProxy:Clusters:product.cluster:Destinations:destination:Address=${PRODUCT_SERVICE}
      - ReverseProxy:Clusters:log.cluster:Destinations:destination:Address=${LOG_SERVICE}

      - RateLimit:PermitLimit=${RATE_LIMIT_PERMIT_LIMIT}
      - RateLimit:Window=${RATE_LIMIT_WINDOW}
      - RateLimit:QueueLimit=${RATE_LIMIT_QUEUE_LIMIT}
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - authservice.api
      - productservice.api
      - logservice.api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
