services:
  
  mssql:
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123456789Abc*
      - MSSQL_PID=Evaluation
  
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_search_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-network
  
  kibana:
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq

  redis:
    container_name: redis
    ports:
      - "6379:6379"

  authservice.api:
    container_name: authserviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      
      - ConnectionStrings:SqlServer=Server=mssql,1433;Database=AuthDB;User Id=sa;Password=123456789Abc*;TrustServerCertificate=True;

      - RabbitMQOptions:Host=rabbitmq
      - RabbitMQOptions:VirtualHost=KayraExport
      - RabbitMQOptions:Password=guest
      - RabbitMQOptions:UserName=guest
      - RabbitMQOptions:LogExchangeName=LogExchange
      
      - AuthOptions:Issuer=http://authservice.api
      - AuthOptions:SecurityKey=top_secret_security_key_top_secret_security_key_top_secret_security_key_top_secret_security_key
      
      - TokenOptions:Issuer=http://authservice.api
      - TokenOptions:AccessTokenValidtyPeriod=15
      - TokenOptions:RefreshTokenValidtyPeriod=30
      - TokenOptions:SecurityKey=top_secret_security_key_top_secret_security_key_top_secret_security_key_top_secret_security_key 
    ports:
      - "5001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

      - ConnectionStrings:SqlServer=Server=mssql,1433;Database=ProductDB;User Id=sa;Password=123456789Abc*;TrustServerCertificate=True;

      - RabbitMQOptions:Host=rabbitmq
      - RabbitMQOptions:VirtualHost=KayraExport
      - RabbitMQOptions:Password=guest
      - RabbitMQOptions:UserName=guest
      - RabbitMQOptions:LogExchangeName=LogExchange
      
      - AuthOptions:Issuer=http://authservice.api
      - AuthOptions:SecurityKey=top_secret_security_key_top_secret_security_key_top_secret_security_key_top_secret_security_key

      - Redis:Host=redis:6379
    ports:
      - "5002:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

networks:
  elk-network:
    driver: bridge


